apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-web-server
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/nirgeier/DevOps-Zero2Hero'
    targetRevision: main
    path: Content/ArgoCD/app  
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
