version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - web-content:/usr/share/nginx/html
    networks:
      - webnet

volumes:
  web-content:

networks:
  webnet:
