apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to Nginx!</title>
    </head>
    <body>
        <h1>Hello from Nginx running in Kubernetes!</h1>
        <p>This is a static HTML page served by Nginx in a kind cluster.</p>
    </body>
    </html>
