apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web-server
  labels:
    app: hello-web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-web-server
  template:
    metadata:
      labels:
        app: hello-web-server
    spec:
      containers:
        - name: hello-web-server
          image: nginx:latest
          ports:
            - containerPort: 80
