#Example for a Kubernetes Secret to provide Argo read permissions to your private repository
apiVersion: v1
kind: Secret
metadata:
  name: private-repo-secret
  namespace: argocd
  annotations:
    managed-by: argocd.argoproj.io # Indicates ArgoCD will manage this secret
  labels:
    argocd.argoproj.io/secret-type: repository # Tells ArgoCD this secret is for a Git repository
type: Opaque # Standard secret type
stringData:
  type: git
  url: git@github.com:<git username>/<repo name>.git # The SSH URL of the private Git repository
  project: default
  sshPrivateKey: |
      -----BEGIN OPENSSH PRIVATE KEY-----
    <paste your private key>
    -----END OPENSSH PRIVATE KEY-----