name: DevOps Quality Checks

on:
  push:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '**/Dockerfile'
      - '**/*.sh'
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '**/Dockerfile'
      - '**/*.sh'
  workflow_dispatch:

#––– security hardening ––––––––––––––––––––––––––––––––––––––––––
permissions:
  contents: read            # least‑privilege token

concurrency:                 # cancel stale runs on the same branch
  group: ${{ github.ref }}
  cancel-in-progress: true
#–––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

jobs:
  lint:
    name: Static analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      #––– Hadolint ––––––––––––––––––––––––––––––––––––––––––––
      - name: Hadolint
        if: ${{ hashFiles('**/Dockerfile') != '' }}
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true

      #––– Yamllint ––––––––––––––––––––––––––––––––––––––––––––
      - name: Yamllint
        if: ${{ hashFiles('**/*.yml', '**/*.yaml') != '' }}
        uses: ibiqlik/action-yamllint@v3

      #––– Actionlint (GitHub workflow linter) –––––––––––––––––
      - name: Actionlint
        if: ${{ hashFiles('.github/workflows/*.yml', '.github/workflows/*.yaml') != '' }}
        uses: rhysd/actionlint@v1
        with:
          shell: bash

      #––– Kubeconform (Kubernetes schema validation) –––––––––
      - name: Kubeconform
        if: ${{ hashFiles('**/*.yml', '**/*.yaml') != '' }}
        uses: hermanbanken/kubeconform-action@v1
        with:
          options: -strict -summary

      #––– ShellCheck ––––––––––––––––––––––––––––––––––––––––––
      - name: ShellCheck
        if: ${{ hashFiles('**/*.sh') != '' }}
        uses: ludeeus/action-shellcheck@v2
